version: ">= 0.14.0"

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-service-epg-policy/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-service-epg-policy/actions/workflows/test.yml)

  *This module is no longer maintained as it has been integrated into the [nac-aci](https://github.com/netascode/terraform-aci-nac-aci) module.*

  # Terraform ACI Service EPG Policy Module

  Manages ACI Service EPG Policy

  Location in GUI:
  `Tenants` » `XXX` » `Policies` » `Protocol` » `L4-L7 Service EPG Policy`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
